/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  DbMon as DbMon
} from './components/db-mon/db-mon';

declare global {
  interface HTMLDbMonElement extends DbMon, HTMLElement {
  }
  var HTMLDbMonElement: {
    prototype: HTMLDbMonElement;
    new (): HTMLDbMonElement;
  };
  interface HTMLElementTagNameMap {
    "db-mon": HTMLDbMonElement;
  }
  interface ElementTagNameMap {
    "db-mon": HTMLDbMonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "db-mon": JSXElements.DbMonAttributes;
    }
  }
  namespace JSXElements {
    export interface DbMonAttributes extends HTMLAttributes {
      
    }
  }
}

